import "./globals.css";
import Navbar from "./components/Navbar/index";
import Footer from "./components/Footer/index";
// import {ClerkProvider} from "@clerk/nextjs";
import {GlobalContextProvider} from "./Context/store";
import React from "react";

export const metadata = {
    title: "Leaders Academy",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        // <ClerkProvider>
            <GlobalContextProvider>
                <html lang="en">
                <body>
                <Navbar/>
                {children}
                <Footer/>
                </body>
                </html>
            </GlobalContextProvider>
        // </ClerkProvider>
    );
}
