import './globals.css';
import Navbar from './components/Navbar/index';
import Footer from './components/Footer/index';
import {ClerkProvider} from '@clerk/nextjs'

export const metadata = {
    title: 'desgy',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <ClerkProvider>
            <html lang="en">
            <body>
            <Navbar/>
            {children}
            <Footer/>
            </body>
            </html>
        </ClerkProvider>
    )
}
